### ISSUE TITLE
After a server restart, already used addresses are reused

### ISSUE THREAD

**Issue by MBuffenoir** [MyceliumGear/straight-server#36]
As you can see in my screenshot, order 13 and 14 reuses the same address than order 2 and 3.
Server has been restarted in between.

here is my config (using latest gem version)
```
gateways_source: config
environment: development
count_orders: false
expiration_overtime: 30
reuse_address_orders_threshold: 20

gateways:
  default:
    # Testing key:
    pubkey: xpub6DU4919Z8P5nHWWpjwdMGosSWyHNpKYJQPpnJbXNeSGKxAFU4qs9LUvTTruHHFM21UyYB3JPNZhq8XFYR9LFeCvWUtjai5Xfs57YUP7nTfY
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: false
    callback_url: 'http://dev.sbex.ch:8002/api/v1/straight/callback/'
    default_currency: 'BTC'
    orders_expiration_period: 600 # seconds

    check_order_status_in_db_first: false # Consider changing to `false` in production.

    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp

    active: true

  #- ChainCom:
  #    api_key_id: cc605dd6fbe765feb77abf99843e9edd
  - BlockchainInfo # uses Straight::Blockchain::BlockchainInfoAdapter
  #Mycelium       # uses Straight::Blockchain::MyceliumAdapter
  # - MyCustomClass::MyCustomBlockchainAdapter

logmaster:
  log_level: INFO # Wise to change to WARN for production
  file: straight.log
  raise_exception: false
  name: Straight server logger

redis:
  host: redis
  port: 6379

db:
  adapter: postgresql
  host: db
  encoding: unicode
  #database: straight
  name: straight
  user: postgres
  password: postgres

```
<img width="1012" alt="screen shot 2015-10-06 at 11 02 03" src="https://cloud.githubusercontent.com/assets/1315271/10304377/016c2406-6c1a-11e5-9023-2218964cc68f.png">
