### ISSUE TITLE
Mainnet address is generated when using a testnet config

### ISSUE THREAD

**Issue by btcontract** [MyceliumGear/straight-server#49]
Hi, this my config.yml setup:

```
gateways:
  default:
    test_pubkey: tpubDAenfwNu5GyCJWv8oqRAckdKMSUoZjgVF5p8WvQwHQeXjDhAHmGrPa4a4y2Fn7HF2nfCLefJanHV3ny1UY25MRVogizB2zRUdAo7Tr9XAjm
...
test_mode: true
```

And this is console output when I create a new order using a form at localhost:9696

> I, [2016-02-10T11:30:20.596964 #18648]  INFO -- : Order 3 created: {:status=>0, :amount=>45000, :address=>"12pc2Qp4U4sFnu9q6HsK8msR2GTqgkgTm7", :tid=>nil, :id=>3, :payment_id=>"1a0d0fc4eaba6375deb408674c57e10a5d0c17ebc283b3cf0baf93de97aa4458", :amount_in_btc=>"0.00045", :amount_paid_in_btc=>"0.0", :keychain_id=>1, :last_keychain_id=>"1"}

I also get this message periodically: 

> I, [2016-02-10T11:33:11.723529 #18648]  INFO -- : Checking status of order 3
> W, [2016-02-10T11:33:12.080438 #18648]  WARN -- : Address seems to be invalid, ignoring it. {:message=>"address in question: 12pc2Qp4U4sFnu9q6HsK8msR2GTqgkgTm7"}

**Comment by AlexanderPavlenko** [comment]
`test_mode` is a per-gateway setting, make sure it's indented properly
```
gateways:
  default:
    test_pubkey: tpubDAenfwNu5GyCJWv8oqRAckdKMSUoZjgVF5p8WvQwHQeXjDhAHmGrPa4a4y2Fn7HF2nfCLefJanHV3ny1UY25MRVogizB2zRUdAo7Tr9XAjm
    test_mode: true
    …
```
